### ISSUE TITLE
access_token endpoint 429s

### ISSUE THREAD

**Issue by freddinator** [SocialiteProviders/Reddit#3]
When I go to my auth endpoint it successfully goes to reddit and returns to my site. However, the call to reddit's access_token endpoint fails:
```
Client error: `POST https://ssl.reddit.com/api/v1/access_token` resulted in a `429 Too Many Requests` response:
{"error": 429}
```

According to [people](https://www.reddit.com/r/redditdev/comments/3qbll8/429_too_many_requests/) in the /r/redditdev subreddit, this can be solved by changing the user agent to something custom.

**Comment by DraperStudio** [comment]
Send a PR since you already know how to fix this.

**Comment by freddinator** [comment]
I would do, but I'm honestly not sure as to the best way to go about this. Reddit's [api guidelines](https://github.com/reddit/reddit/wiki/API) require a "unique and descriptive" useragent including the target platform, a unique application identifier, a version string, and your username as contact information, in the following format:
`<platform>:<app ID>:<version string> (by /u/<reddit username>)`

**Comment by DraperStudio** [comment]
You could add `REDDIT_PLATFORM`, `REDDIT_APP_ID` and `REDDIT_VERSION_STRING` to the `.env` file and then access them via `$this->getConfig('platform');` for example to add them to the Guzzle Client instance.
