### ISSUE TITLE
addtionalConfigKeys should be optional

### ISSUE THREAD

**Issue by jolora** [SocialiteProviders/Reddit#8]
If I attempt to redirect with Reddit I receive the following error:

> Configuration for REDDIT_PLATFORM is missing.
> Missing services entry for reddit.platform

If I comment out the additionalConfigKeys() function in Provider.php everything works as expected. These additional config keys should be optional.

**Comment by jolora** [comment]
Why was this issue closed?

Every time I run composer update I receive the same error, until I comment out the additionalConfigKeys from Provider.php. 

The provider works fine if I do that, but should I be adding additional keys to my .env as best practice with Reddit? There is no mention of additional config in the provider's docs.

I know you're not obliged to reply or anything... free software and all that. But I would really appreciate an explanation if you have the time. Thanks.

**Comment by DraperStudio** [comment]
There is no need to remove the complete function, just add `REDDIT_PLATFORM=` to your .env file if you don't need it, we will add support for optional fields in the future.

**Comment by jolora** [comment]
Thanks for your response.

FYI: I attempted adding REDDIT_PLATFORM= to the .env file before. I just tried again, but the error persisted.
